name: Access Tokens for GitHub Actions
description: GitHub Action to request temporary access tokens
author: qoomon
branding:
  icon: unlock
  color: blue
inputs:
  organization:
    description: Target organization, e.g. sesame-street
    required: true
  repository:
    description: Target repository, e.g. sesame-street/playground
    required: true
  repositories:
    description: |-
      Target repositories as YAML array string, e.g. 
      repositories: |  
        - sesame-street/playground
        - sesame-street/shop
    required: true
  permissions:
    description: |-
      The permissions to request as YAML object string, e.g. 
      permissions: |
        actions: write
    required: true
outputs:
  token:
    description: The requested access token
runs:
  using: node20
  main: action/dist/index.js
