name: Action > Build

on:
  push:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: action
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: action
          sparse-checkout-cone-mode: false

      # build the action
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: action/package-lock.json
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run test
      - run: npm run build

      # Verify that the dist/ is up-to-date
      - run: |
          git_diff="$(git diff --name-only dist/)"
          if [ -n "$git_diff" ]; then
            echo "Drift detected in dist/ directory"
            exit 1
          fi
