on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # daily at 12:00
  push:
    branches:
      - main

jobs:
  RepoAccess:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      id-token: write
    steps:
      - uses: .
        id: access-token
        with:
          permissions: |
            secrets: write

      - run: >-
          gh secret set RAINBOW_API_KEY 
          --body "Unicorn-$(date +%s)"
          --app actions
          --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ steps.access-token.outputs.token }}
