on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  RepoAccess:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: qoomon/actions--access-token@main
        id: access-token
        with:
          permissions: |
            secrets: write

      - run: >-
          gh secret set RAINBOW_API_KEY 
          --body "Unicorn-$(date +%s)"
          --app actions
          --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ steps.access-token.outputs.token }}
